version: "3.1"

services:
  db:
    image: mysql:5.7.42
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=movies_user
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=movies
    volumes:
      # folder of my database
      - ./var/db-data:/var/lib/mysql:rw
      # configuration file
      - ./my.cnf:/etc/mysql/my.cnf
    ports:
      - 3306:3306
